# Snakefile
rule run_container:
    output:
        "output/stdout.txt"
    container: 
        "docker://ghcr.io/navarroc/l2c-example-1:amd64"
    shell:
        """
        ./run_tool.sh > {output}
        """
