# Snakefile
rule run_container:
    output:
        "output/stdout.txt"
    container: 
        "docker://hub.ncsa.illinois.edu/farmdoc/l2c-example-1:amd64"
    shell:
        """
        ./run_tool.sh > {output}
        """
