# Snakefile
rule run_container:
    output:
        "output/stdout.txt"
    singularity:
        "l2c-example-1_latest.sif"
    resources:
        slurm_partition="IllinoisComputes",
        runtime=5,
        mem_mb=4000,
        cpus_per_task=1,
        slurm_account="ncsa-ic",
        nodes=1
    shell:
        """
        ./run_tool.sh > {output}
        """
